apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
  namespace: "estudajegue"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}    